# -*- coding: utf-8 -*-
"""bug_hunt.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJcCCWZDaQzAzIIA51Mja5dKr3Z0EAin
"""

print("Welcome to the Bug Hunt!") # BUG: There was a syntax error since the last quotation is missing; I fixed it by adding the missing quote
name = input("What is your name? ")
print(f"Nice to meet you, {name}") # Bug: f-string was forgotten, and the name variable was misspelled, and I corrected them
age = int(input("How old are you? ")) # Bug: age variable was not typecast to int since it is a number
print("Next year you will be ", age + 1)

