# -*- coding: utf-8 -*-
"""ticket_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKq6mpu41l94a-kUnB541SsvSF2MyBob
"""

age = int(input("Type your age here: "))
is_adult = age >= 18
if is_adult:
  print("Pay the full ticket price")

else:
  print("Pay the child's ticket price")

